### ISSUE TITLE
Malá prosba: používat pokud možno více unikátní id speakerů

### ISSUE THREAD

**Issue by burningtree** [utxo-foundation/utxo-prague#33]
Vyhnout se tedy tomu aby `id` bylo jen nějaké bězné slovo, typicky křestní jméno. V rámci PBW se podle ID párují speakeři a mohlo by to vyvolat kolizi. Zbytečně se to pak musí overridovat.  

Příklad:
* `nikola` -> ❌ 
* `jan` -> ❌ 
* `jan-21m` -> ✅
* `huge` -> ✅
* `damsky` -> ✅   
* `fetyas` -> ✅   

V současné db utxo23 vidím zatím jen jeden takový záznam a to je [`nikola`](https://github.com/utxo-foundation/utxo-prague/blob/35951862063a7feca4b2ea597966b1f05c2e9112/spec/23/speakers.yaml#L709), v tomhle případě bych doporučil použít nickname jako id, tedy `bihanojko` (pokud je nickname známější než jméno, použijte nickname).

https://github.com/utxo-foundation/utxo-prague/blob/35951862063a7feca4b2ea597966b1f05c2e9112/spec/23/speakers.yaml#L709-L713

Jen pár thoughts. Díky moc 🙏

**Comment by burningtree** [comment]
Je to problém?

**Comment by cryptonda** [comment]
není problém, fixnuto, sorry předtím jsem to přehlídnul
